# Generated by Django 3.2 on 2023-03-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'ordering': ('id',), 'verbose_name': 'Коментарий к отзыву'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('id',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
